
import React from 'react';
import { LayoutDashboard, Dumbbell, Users, Settings, Trophy, Activity, MessageSquare, Clock3, Shield, Bot, BarChart3, History } from 'lucide-react';
import { NavItem, Badge, LeaderboardEntry, WorkoutHistoryEntry, UserRole } from './types';

export const TRANSLATIONS = {
  en: {
    appName: "DOLPHIN GYM",
    welcome: "Welcome back,",
    dashboard: "Dashboard",
    workouts: "Workouts",
    equipment: "Equipment",
    trainers: "Trainers",
    members: "Players",
    admin: "Manager Panel",
    trainer: "Trainer Panel",
    trainee: "Player Member",
    stats: "Analytics",
    settings: "Settings",
    aiCoach: "AI Personal Coach",
    history: "Workout History",
    totalWorkouts: "Total Sessions",
    caloriesBurned: "Calories Burned",
    avgDuration: "Avg Duration",
    recentActivity: "Recent Activity",
    activeMembers: "Active Players",
    gymCapacity: "Gym Capacity",
    language: "Language",
    logout: "Sign Out",
    profile: "My Profile",
    goal: "Fitness Goal",
    weight: "Weight",
    height: "Height",
    kg: "kg",
    cm: "cm",
    mins: "mins",
    sets: "Sets",
    reps: "Reps",
    startWorkout: "Start Workout",
    exerciseDetails: "Exercise Details",
    status: "Status",
    available: "Available",
    maintenance: "In Maintenance",
    broken: "Out of Order",
    inUse: "In Use",
    manageUsers: "Manage Players",
    manageEquipment: "Inventory & Devices",
    reports: "System Reports",
    askCoach: "Ask your AI Coach anything...",
    send: "Send",
    login: "Login",
    signup: "Sign Up",
    email: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    elitePoints: "Gym Points",
    badges: "Achievements",
    leaderboard: "Leaderboard",
    rank: "Rank",
    unlocked: "Unlocked",
    locked: "Locked",
    pointsEarned: "Points Earned",
    congrats: "Congratulations!",
    milestone: "New Milestone Reached",
    ep: "GP",
    subscription: "Subscription",
    startDate: "Start Date",
    endDate: "End Date",
    expiryAlert: "Subscription expiring soon!",
    addMember: "Add New Player",
    editMember: "Edit Player Info",
    memberName: "Player Name",
    save: "Save Player",
    daysLeft: "days left",
    notifications: "Notifications",
    expiryNotifyToggle: "Push Notifications",
    notifyEnabled: "Enabled",
    notifyDisabled: "Disabled",
    searchMembers: "Search players...",
    expiryDaysLabel: "Alert days before expiry",
    expiringIn: "expiring in",
    assignedTrainees: "My Players",
    traineeProgress: "Player Progress",
    assignWorkout: "Assign Workout",
    viewProgress: "View Progress",
    management: "Management",
    renew: "Renew +30D",
    active: "Active",
    expired: "Expired",
    all: "All",
    expiring: "Expiring",
    delete: "Remove",
    confirmDelete: "Are you sure you want to remove this player?",
    update: "Update",
    testNotify: "Send Test Notification",
    notifyTitle: "Dolphin Gym Alert",
    memberExpiryMsg: "Your subscription ends in {{days}} days. Renew now!",
    adminExpiryMsg: "{{count}} player subscriptions end in less than {{days}} days.",
    testNotifyMsg: "Push notifications for Dolphin Gym are active!",
    paymentMethod: "Payment Method",
    cash: "Cash",
    click: "Click",
    changeEmail: "Change Email",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    security: "Account Security",
    updateProfile: "Update Profile",
    personalInfo: "Personal Information",
    saveChanges: "Save Changes",
    currentPassword: "Current Password",
    traineeAccountSettings: "Player Account Settings",
    resetPassword: "Reset Password",
    forceUpdateEmail: "Override Email",
    adminAccess: "Manager Privileges",
    success: "Operation Successful",
    shareApp: "Invite a Friend",
    shareAppDesc: "Share the Dolphin experience and earn 500 GP",
    invite: "Send Invite",
    community: "Community & Sharing",
    scanPlayer: "Scan Player QR",
    scanning: "Scanning...",
    alignQR: "Align QR Code",
    accessGranted: "Access Granted",
    invalidToken: "Invalid Token",
    scanDescription: "Using secure encrypted scanning protocol v2.4",
    addEquipment: "Add Equipment",
    equipmentName: "Device Name",
    category: "Category",
    strength: "Strength",
    cardio: "Cardio",
    flexibility: "Flexibility",
    weights: "Free Weights",
    inventory: "Gym Inventory",
    lastMaintenance: "Last Service",
    quantity: "Qty",
    maintenanceShort: "Maint.",
    totalEquipment: "Total Assets",
    brokenDevices: "Broken",
    underMaintenance: "Repairing"
  },
  ar: {
    appName: "دولفين جيم",
    welcome: "مرحباً بعودتك،",
    dashboard: "لوحة التحكم",
    workouts: "التمارين",
    equipment: "المعدات",
    trainers: "المدربين",
    members: "اللاعبين",
    admin: "لوحة المدير",
    trainer: "لوحة المدرب",
    trainee: "عضو لاعب",
    stats: "التحليلات",
    settings: "الإعدادات",
    aiCoach: "مدرب الذكاء الاصطناعي",
    history: "سجل التمارين",
    totalWorkouts: "إجمالي الجلسات",
    caloriesBurned: "السعرات المحروقة",
    avgDuration: "متوسط المدة",
    recentActivity: "النشاط الأخير",
    activeMembers: "اللاعبين النشطين",
    gymCapacity: "سعة الصالة",
    language: "اللغة",
    logout: "تسجيل الخروج",
    profile: "ملفي الشخصي",
    goal: "هدف اللياقة",
    weight: "الوزن",
    height: "الطول",
    kg: "كجم",
    cm: "سم",
    mins: "دقيقة",
    sets: "جولات",
    reps: "تكرار",
    startWorkout: "ابدأ التمرين",
    exerciseDetails: "تفاصيل التمرين",
    status: "الحالة",
    available: "متاح",
    maintenance: "قيد الصيانة",
    broken: "خارج الخدمة",
    inUse: "قيد الاستخدام",
    manageUsers: "إدارة اللاعبين",
    manageEquipment: "الجرد والأجهزة",
    reports: "تقارير النظام",
    askCoach: "اسأل مدربك الذكي عن أي شيء...",
    send: "إرسال",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    elitePoints: "نقاط الجيم",
    badges: "الإنجازات",
    leaderboard: "متصدرين",
    rank: "الترتيب",
    unlocked: "تم الفتح",
    locked: "مقفل",
    pointsEarned: "النقاط المكتسبة",
    congrats: "تهانينا!",
    milestone: "تم تحقيق إنجاز جديد",
    ep: "نقطة",
    subscription: "الاشتراك",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    expiryAlert: "سينتهي الاشتراك قريباً!",
    addMember: "إضافة لاعب جديد",
    editMember: "تعديل بيانات اللاعب",
    memberName: "اسم اللاعب",
    save: "حفظ اللاعب",
    daysLeft: "أيام متبقية",
    notifications: "التنبيهات",
    expiryNotifyToggle: "تنبيهات الدفع",
    notifyEnabled: "مفعّل",
    notifyDisabled: "معطّل",
    searchMembers: "البحث عن لاعبين...",
    expiryDaysLabel: "أيام التنبيه قبل الانتهاء",
    expiringIn: "تنتهي خلال",
    assignedTrainees: "لاعبيني",
    traineeProgress: "تقدم اللاعبين",
    assignWorkout: "تعيين تمرين",
    viewProgress: "عرض التقدم",
    management: "الإدارة",
    renew: "تجديد +٣٠ يوم",
    active: "نشط",
    expired: "منتهي",
    all: "الكل",
    expiring: "منتهي قريباً",
    delete: "حذف",
    confirmDelete: "هل أنت متأكد من حذف هذا اللاعب؟",
    update: "تحديث",
    testNotify: "إرسال تنبيه تجريبي",
    notifyTitle: "تنبيه دولفين جيم",
    memberExpiryMsg: "ينتهي اشتراكك خلال {{days}} أيام. جدد الآن!",
    adminExpiryMsg: "ينتهي اشتراك {{count}} لاعبين خلال أقل من {{days}} أيام.",
    testNotifyMsg: "تم تفعيل تنبيهات دولفين جيم بنجاح!",
    paymentMethod: "طريقة الدفع",
    cash: "نقدي",
    click: "كليك",
    changeEmail: "تغيير البريد الإلكتروني",
    changePassword: "تغيير كلمة المرور",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    security: "أمان الحساب",
    updateProfile: "تحديث الملف الشخصي",
    personalInfo: "المعلومات الشخصية",
    saveChanges: "حفظ التغييرات",
    currentPassword: "كلمة المرور الحالية",
    traineeAccountSettings: "إعدادات حساب اللاعب",
    resetPassword: "إعادة تعيين كلمة المرور",
    forceUpdateEmail: "تجاوز البريد الإلكتروني",
    adminAccess: "صلاحيات المدير",
    success: "تمت العملية بنجاح",
    shareApp: "دعوة صديق",
    shareAppDesc: "شارك تجربة دولفين واكسب ٥٠٠ نقطة",
    invite: "إرسال دعوة",
    community: "المجتمع والمشاركة",
    scanPlayer: "مسح رمز اللاعب",
    scanning: "جاري المسح...",
    alignQR: "قم بمحاذاة الرمز",
    accessGranted: "تم السماح بالدخول",
    invalidToken: "رمز غير صالح",
    scanDescription: "استخدام بروتوكول مسح مشفر آمن v2.4",
    addEquipment: "إضافة جهاز",
    equipmentName: "اسم الجهاز",
    category: "الفئة",
    strength: "قوة بدنية",
    cardio: "لياقة (كارديو)",
    flexibility: "مرونة",
    weights: "أوزان حرة",
    inventory: "جرد الصالة",
    lastMaintenance: "آخر صيانة",
    quantity: "الكمية",
    maintenanceShort: "صيانة",
    totalEquipment: "إجمالي الأجهزة",
    brokenDevices: "خارج الخدمة",
    underMaintenance: "تحت الصيانة"
  }
};

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', icon: <LayoutDashboard size={20} />, labelEn: 'Home', labelAr: 'الرئيسية' },
  { id: 'workouts', icon: <Dumbbell size={20} />, labelEn: 'Training', labelAr: 'التمارين' },
  { id: 'coach', icon: <Bot size={20} />, labelEn: 'Coach', labelAr: 'المدرب' },
  { id: 'admin', icon: <Settings size={20} />, labelEn: 'Manage', labelAr: 'الإدارة' },
  { id: 'settings', icon: <Shield size={20} />, labelEn: 'Settings', labelAr: 'الإعدادات' }
];

export const getFilteredNavItems = (role: UserRole): NavItem[] => {
  if (role === 'member') {
    return NAV_ITEMS.filter(item => item.id !== 'admin');
  }
  return NAV_ITEMS;
};

export const MOCK_HISTORY: WorkoutHistoryEntry[] = [
  { id: 'h1', workoutId: 'w1', title: 'Alpha Strength', date: '2024-05-20T08:30:00Z', duration: '45', calories: 320, category: 'Strength' },
  { id: 'h2', workoutId: 'w2', title: 'Dolphin Burn', date: '2024-05-18T17:15:00Z', duration: '30', calories: 450, category: 'Cardio' },
  { id: 'h3', workoutId: 'w1', title: 'Alpha Strength', date: '2024-05-17T07:00:00Z', duration: '50', calories: 350, category: 'Strength' },
];

export const MOCK_BADGES: Badge[] = [
  { id: 'b1', nameEn: 'Early Bird', nameAr: 'طائر مبكر', icon: '🌅', descriptionEn: 'Completed a workout before 8 AM', descriptionAr: 'أكمل تمرينًا قبل الساعة 8 صباحًا', unlocked: true },
  { id: 'b2', nameEn: 'Iron Lifter', nameAr: 'رافع الحديد', icon: '🏋️', descriptionEn: 'Lifted total of 10,000kg in a month', descriptionAr: 'رفع ما مجموعه 10,000 كجم في شهر', unlocked: true },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { id: 'l1', name: 'Alex Thompson', points: 15420, avatar: 'https://i.pravatar.cc/150?u=1', rank: 1 },
  { id: 'l2', name: 'Sara Ahmed', points: 14200, avatar: 'https://i.pravatar.cc/150?u=2', rank: 2 },
  { id: 'l3', name: 'You', points: 8450, avatar: 'https://i.pravatar.cc/150?u=4', rank: 3, isCurrentUser: true },
];

export const MOCK_WORKOUTS = [
  {
    id: 'w1',
    title: 'Alpha Strength',
    duration: '45',
    calories: 320,
    category: 'Hypertrophy',
    exercises: [
      { id: 'e1', name: 'Bench Press', sets: 4, reps: 10, instructions: 'Push weight upwards' },
      { id: 'e2', name: 'Overhead Press', sets: 3, reps: 12, instructions: 'Push above head' }
    ]
  },
  {
    id: 'w2',
    title: 'Dolphin Burn',
    duration: '30',
    calories: 450,
    category: 'Cardio',
    exercises: [
      { id: 'e3', name: 'Burpees', sets: 5, reps: 20, instructions: 'Full body movement' }
    ]
  }
];

export const CHART_DATA = [
  { name: 'Mon', calories: 240, duration: 45 },
  { name: 'Tue', calories: 300, duration: 60 },
  { name: 'Wed', calories: 200, duration: 30 },
  { name: 'Thu', calories: 278, duration: 50 },
  { name: 'Fri', calories: 189, duration: 40 },
  { name: 'Sat', calories: 439, duration: 90 },
  { name: 'Sun', calories: 210, duration: 35 },
];
